config/routes.rb
ReadingApp::Application.routes.draw do
  resources :quizzes

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  attr_accessible :content, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quizzes }
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/new
  # GET /quizzes/new.json
  def new
    @quiz = Quiz.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = Quiz.find(params[:id])
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(params[:quiz])

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render json: @quiz, status: :created, location: @quiz }
      else
        format.html { render action: "new" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quizzes/1
  # PUT /quizzes/1.json
  def update
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      if @quiz.update_attributes(params[:quiz])
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper

	avg_wpm_prose = 300
	avg_wpm_scren = 180
	your_avg_wpm = 0



	def wpm_calc(min,sec,word_count)
		word_count = word_count.to_f
		min = min.to_i
		sec = sec.to_i 
		min_sec = min*60
		total_seconds = sec + min_sec
		wpm = word_count/total_seconds*60
		return wpm.to_i
	end

	def time_now
		time = Time.now().strftime("%H:%M:%S")
	end

	def start_at

	end

	def finished_at
	end

	def time_quant(wpm,word_count)
		sec = word_count/wpm.to_f*60
		time = Time.at(sec).strftime("%M:%S")
	end

	def compare(current_wpm,nat_wpm)
		you = current_wpm.to_f
		them = nat_wpm.to_f
		k = you/them*100
		k = k.to_i
		return k
	end

	# 
	# button "start" do
	# 	@time = Time.now
	# 	@label.replace "Started at #{@time.strftime '%l:%M:%S %p'}"
	# end

	# button "stop" do
	# 	@label.replace "Stopped, ", strong("#{Time.now - @time}"),
	# 	" seconds elapsed."
	# end 
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadingApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/_stopwatch.html.erb
<p>
	<span id="watchdisplay">00:00:00</span> 
	<input onclick="w.start()" type="button" value="Start" /> 
	<input onclick="w.stop()" type="button" value="Stop" /> 
	<script type="text/javascript">// <![CDATA[
		function updatedisplay(watch) {
		document.getElementById('watchdisplay').innerHTML = watch.toString() + "." + parseInt(watch.getElapsed().milliseconds/100);
		}
	var w = new Stopwatch(updatedisplay, 50);
	// ]]&gt;</script>
</p>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Listing quizzes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quizzes.each do |quiz| %>
  <tr>
    <td><%= quiz.name %></td>
    <td><%= quiz.content %></td>
    <td><%= link_to 'Show', quiz %></td>
    <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
    <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>
<% @current_word_count = @quiz.content.split(' ').count	 %>
<% avg_wpm_prose = 300;
est_time = time_quant(avg_wpm_prose,@current_word_count) %>



  <% temp = wpm_calc('3','45',@current_word_count) %>
  <% time_quant(temp,@current_word_count) %>

<p> The time is now <%= elmo = time_now %> </p>


<p>
  <b>Name:</b>
  <%= @quiz.name %>
</p>

<p>
  <b>Content:</b>
  <p>There are currently <%= @current_word_count %> words in this passage </p>
  <p> It should take you <%= est_time %> to finish the average being <%= avg_wpm_prose %> wpm</p>
  <%= @quiz.content %>
</p>

<%= render 'quizzes/stopwatch' %>


<!-- <iframe width="100%" height="300" src="http://jsfiddle.net/QUhjx/embedded/" allowfullscreen="allowfullscreen" frameborder="0"></iframe> -->





<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>